### ISSUE TITLE
@vercel/kv Docker image for local development

### ISSUE THREAD

**Issue by sebpalluel** [vercel/storage#281]
I'm really interested by your SDK but i've noticed that you need to use an URL and Token from Vercel and i see no option to connect a Redis instance directly.
I'm used to work with local containers for postgres and redis through docker-compose, which is best for many reason including for tests and the ability to work even with a degraded internet connection.
Do you plan to release a docker image for `@vercel/kv` or at least a way to connect to a local redis instance ?

**Comment by coreh** [comment]
Since Vercel KV is based on the `@upstash/redis` library, you can use [Serverless Redis HTTP (SRH)](https://github.com/hiett/serverless-redis-http) to run a local HTTP endpoint for development. (See: https://docs.upstash.com/redis/sdks/javascriptsdk/developing-or-testing)

This is my current `docker-compose.yml` setup:

```yaml
version: '3.1'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  serverless-redis-http:
    ports:
      - '8079:80'
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: 'redis://redis:6379' # Using `redis` hostname since they're in the same Docker network.
```

You can then connect with the following environment variables:

```sh
KV_REST_API_URL="http://localhost:8079"
KV_REST_API_TOKEN="example_token"
```

**Comment by sebpalluel** [comment]
> Since Vercel KV is based on the `@upstash/redis` library, you can use [Serverless Redis HTTP (SRH)](https://github.com/hiett/serverless-redis-http) to run a local HTTP endpoint for development. (See: https://docs.upstash.com/redis/sdks/javascriptsdk/developing-or-testing)
> 
> This is my current `docker-compose.yml` setup:
> 
> ```yaml
> version: '3.1'
> 
> services:
>   redis:
>     image: redis
>     ports:
>       - '6379:6379'
> 
>   serverless-redis-http:
>     ports:
>       - '8079:80'
>     image: hiett/serverless-redis-http:latest
>     environment:
>       SRH_MODE: env
>       SRH_TOKEN: example_token
>       SRH_CONNECTION_STRING: 'redis://redis:6379' # Using `redis` hostname since they're in the same Docker network.
> ```
> 
> You can then connect with the following environment variables:
> 
> ```shell
> KV_REST_API_URL="http://localhost:8079"
> KV_REST_API_TOKEN="example_token"
> ```

Thanks for your solution, I will try it out !
That would be good to have it in the doc as it was clearly an issue that kept me out of using this service on the first place.

**Comment by vvo** [comment]
Hey there, we're looking at adding pages for both postgres and kv about local development, will keep you posted

**Comment by tweeres04** [comment]
> Since Vercel KV is based on the `@upstash/redis` library, you can use [Serverless Redis HTTP (SRH)](https://github.com/hiett/serverless-redis-http) to run a local HTTP endpoint for development. (See: https://docs.upstash.com/redis/sdks/javascriptsdk/developing-or-testing)

Upstash developing or testing page has moved to: https://upstash.com/docs/oss/sdks/ts/redis/developing

**Comment by jpchavat** [comment]
> Hey there, we're looking at adding pages for both postgres and kv about local development, will keep you posted

any progress, @vvo ?

**Comment by 0x33dm** [comment]
> > Hey there, we're looking at adding pages for both postgres and kv about local development, will keep you posted
> 
> 
> 
> any progress, @vvo ?

Not being able to work offline is a deal breaker. 

Being able to run tests offline is quite an important when  developing an API.

**Comment by kerkkoh** [comment]
@0x33dm The docker container solution by @coreh above works as of `2024-04-20`. Simply download [Docker desktop](https://docs.docker.com/desktop/), and in your project directory root, create a file called `docker-compose.yml` and copy & paste the contents:
```yml
version: '3.1'

services:
  # This is the local Redis database that will be running on your computer; Within docker it has the hostname `redis` and it exposes the port 6379 to your pc and other containers
  redis:
    image: redis
    ports:
      - '6379:6379'

  # This is the serverless router that allows the Vercel KV libraries to send queries to the redis server above (redis:6379)
  # It uses the port 80 internally, so it is mapped to an arbitrary port 8079, so that it doesn't conflict with your potential web app on port 80
  # Think of this as local Vercel KV, and you could even rename this to local-vercel-kv if that helps you to understand this structure
  serverless-redis-http:
    ports:
      - '8079:80'
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token # This is your local Vercel KV instance's API token (KV_REST_API_TOKEN), and you can change it to anything or keep it as is for development
      SRH_CONNECTION_STRING: 'redis://redis:6379' # Using `redis` hostname since they're in the same Docker network.
```

Now when you have Docker Desktop (or other version of Docker) installed and running, simply open up a command line (bash/cmd/terminal) and navigate to the directory where you placed the `docker-compose.yml` file, and execute the following command:

`docker-compose up`

Now you should see Docker downloading the needed images, and ultimately the local Vercel KV instance starts running.

Finally, within your project of choice, expose the 2 system variables required for the @vercel/kv library to connect to your local KV instance in a `.env` file for example like above:
```sh
KV_REST_API_URL="http://localhost:8079"
KV_REST_API_TOKEN="example_token"
```

Hopefully this further explanation helps you out! This docker solution is the best one right now (and probably in the future) as you can deploy this locally on any operating system. If you have any questions, let me know.

As @tweeres04 kindly pointed out, you can also find a similar setup that will work with @vercel/kv in the Upstash documentation https://upstash.com/docs/oss/sdks/ts/redis/developing.

  Vercel KV itself is simply a dumbed down wrapped version of Upstash, so generally anything that applies to Upstash will apply to Vercel KV. If you want to find out more, I'd suggest looking at what you get with Upstash directly instead of using Vercel KV as a wrapper. _Disclaimer: I have nothing against Vercel KV, and use it in production_
